CREATE TABLE OrderLogs (
    LogID INT IDENTITY(1,1) PRIMARY KEY,
    OrderID INT,
    CreatedAt DATETIME DEFAULT GETDATE()
);
GO

CREATE TRIGGER trg_LogOrderCreate
ON Orders
AFTER INSERT
AS
BEGIN
    INSERT INTO OrderLogs (OrderID)
    SELECT ID FROM INSERTED;
END
GO
